# Huffman Coding Library
from typing import Protocol, List
from lib.Huffman import Huffman, HuffmanNode


class HuffmanProtocol(Protocol):
    """Protocol defining the interface for Huffman coding dependency injection"""
    def train(self, tokens: List[str]) -> dict: ...
    def encode(self, tokens: List[str]) -> str: ...
    def decode(self, binary_string: str) -> List[str]: ...
    def get_codebook(self) -> dict: ...
    def load_codebook(self, codebook: dict) -> None: ...
    def serialize_codebook(self) -> str: ...
    def deserialize_codebook(self, binary_string: str) -> str: ...


__all__ = ['Huffman', 'HuffmanNode', 'HuffmanProtocol']
